### ISSUE TITLE
Compile errors in Font.cpp

### ISSUE THREAD

**Issue by aubade** [Jebbs/DSFML-C#3]
Sorry to bug you again, but trying to compile with GCC 4.7 is giving me some errors:

/home/erika/Devel/DSFML-C/src/SFML/Graphics/Font.cpp:68:33: error: ‘sfFont\* sfFont_createFromStream’ redeclared as different kind of symbol
In file included from /home/erika/Devel/DSFML-C/src/SFML/Graphics/Font.cpp:33:0:
/home/erika/Devel/DSFML-C/include/SFML/Graphics/Font.h:51:28: error: previous declaration of ‘sfFont\* sfFont_createFromStream(void*)’
/home/erika/Devel/DSFML-C/src/SFML/Graphics/Font.cpp:68:33: error: ‘DStream’ was not declared in this scope
/home/erika/Devel/DSFML-C/src/SFML/Graphics/Font.cpp:68:42: error: ‘stream’ was not declared in this scope
